### ISSUE TITLE
Obsidian links inside table cells not handling the escaping of |

### ISSUE THREAD

**Issue by mark-climateview** [GooRoo/mkdocs-obsidian-bridge#13]
Hi,

I encountered a bug with Obsidian links inside tables. I have an Obsidian Markdown code fragment that looks like this:

```
| index | title                                                                              | reference   |
| ----- | ---------------------------------------------------------------------------------- | ----------- |
| 1     | Bioenergy and BECCS                                                                | AR6 7.4.4   |
| 2     | [[ipcc/m-2c2-shift-sustainable-healthy-diets\|Shift to sustainable healthy diets]] | AR6 7.4.5.1 |
| 3     | Reduce food loss and waste                                                         | AR6 7.4.5.2 |
| 4     | Improved and enhanced use of wood products                                         | AR6 7.4.5.3 |

```

The output I was expecting:

```
<tr>
<td>2</td>
<td><a href="http://localhost:8000/ipcc/m-2c2-shift-sustainable-healthy-diets">Shift to sustainable healthy diets</a></td>
<td>AR6 7.4.5.1</td>
</tr>
```

The output I received:

```
<tr>
<td>2</td>
<td><a href="http://localhost:8000/ipcc/m-2c2-shift-sustainable-healthy-diets%5C">Shift to sustainable healthy diets</a></td>
<td>AR6 7.4.5.1</td>
</tr>
```

I.e. the escaped "|" character in the link was broken apart by the regexp leaving a trailing "\" matched onto the filepath which MkDocs then (presumably?) later escaped to "%5C" which resulted in a broken link.

I might have a possible fix, but I'm not confident enough with regular expressions to be certain it is the right type of fix or that I'm not breaking something else. The fix I tested locally was to change the following line in plugin.py from:

```
OBSIDIAN_LINK = (
                r'\[\[(?P<filepath>[^\]#\|]*)(?P<fragment>\#(?P<fragment_text>[^\|\]]+))*(?:\|(?P<label>[^\]]*))*\]\]'
            )
```

to:

```
OBSIDIAN_LINK = (
                r'\[\[(?P<filepath>[^\]#\|\\]*)(?P<fragment>\#(?P<fragment_text>[^\|\\\]]+))*\\?(?:\|(?P<label>[^\]]*))*\]\]'
            )

```

That is, filepath and fragment_text should not contain any backslashes, and an optional backslash is accepted before the |.  Is this a reasonable fix or will it break legitimate filepaths with escaped characters?

**Comment by GooRoo** [comment]
I'll investigate how Obsidian behaves in this and similar cases and will see if the fix proposed by you is sufficient. On this weekend, perhaps. 
Thanks!

**Comment by GooRoo** [comment]
Okay, so I've just found out that there is a bug on Obsidian side too.

It **is** possible to use `\` as a path separator in obsidian-style links like so:
```md
[[some\sub\folder\Page]]
```
However, even if `some/sub/folder/Page.md` exists, Obsidian thinks it does not. And if you click the link like this, it will create `Page 1.md` next to the `Page.md`, then `Page 2.md`, `Page 3.md`, and so on. 

In other words, Obsidian resolves the path with back-slashes differently in certain situations. I think I have no other choice except to ignore this weird behavior.

**Comment by mark-climateview** [comment]
That fix worked like a charm! Thanks for the swift help.
