### ISSUE TITLE
Can't resolve link for index.md and README.md

### ISSUE THREAD

**Issue by ndy2** [GooRoo/mkdocs-obsidian-bridge#4]
I really like this plugin and your approach and `Auto-expand Link` Feature.

I found that it can't handle the link for index.md or README.md properly.
As you might can see in this [link](https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages), mkdocs has a page called index page for each directory. A Index page literally work as `index page` of the path, so has different logic for it's path.

If `docs/ ` has bellow documents,
```
- 'index.md'
- 'a.md'
- folder
    - 'README.md`
    - `b.md`
```

then for each document gets following link by mkdocs

- `index.md` - `/`
- `a.md` - `/a`
- `floder/README.md` - `/folder`
- `floder/b.md` - `/folder/b`

but it seems that this plugin tries with

- `index.md` - `/index`
- `a.md` - `/a`
- `floder/README.md` - `/folder/README`
- `floder/b.md` - `/folder/b`

for each document
and get failure (or try its best to resolve link)

Can you please resolve this issue?

**Comment by GooRoo** [comment]
Thanks for the reported issue. I'll try to look into it during the weekend.

**Comment by GooRoo** [comment]
I actually found out that my algorithm works not exactly as it's supposed to (not as I wanted).
It doesn't take into account the partial path provided and instead relies only on the file name. Need to rewrite it.
